---
- name: Install Helm
  hosts: servers
  become: yes

  tasks:
    - name: Install curl
      package:
        name: curl
        state: present

    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '700'

    - name: Run Helm installation script
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm
      register: helm_install_result
      changed_when: false
